### ISSUE TITLE
[AutomationTestRunServlet] Error trying to start nodes: java.lang.NullPointerException

### ISSUE THREAD

**Issue by dquiles** [RetailMeNot/SeleniumGridScaler#9]
Ive compiled the project, populated src/main/resources/aws.properties.default and startGrid with modified vars. The output shows the correct data as far as subnet, ami, security group, but I keep running into an error. Any insight would be greatly appreciated, tyia.

curl -v -L -G -d "uuid=testRun1&threadCount=2&browser=chrome&os=linux" http://localhost:4444/grid/admin/AutomationTestRunServlet

* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 4444 (#0)
> GET /grid/admin/AutomationTestRunServlet?uuid=testRun1&threadCount=2&browser=chrome&os=linux HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:4444
> Accept: */*
>
< HTTP/1.1 500 Nodes could not be started: null
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html;charset=ISO-8859-1
< Content-Length: 1348
* Server Jetty(7.x.y-SNAPSHOT) is not blacklisted
< Server: Jetty(7.x.y-SNAPSHOT)
<
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 Nodes could not be started: null</title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /grid/admin/AutomationTestRunServlet. Reason:
<pre>    Nodes could not be started: null</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
...snip whitespace...
</body>
</html>
* Connection #0 to host localhost left intact

./starGrid
...snip...
Apr 21, 2015 19:49:05:907 PM - INFO  [main] [Server] jetty-7.x.y-SNAPSHOT
Apr 21, 2015 19:49:05:942 PM - INFO  [main] [ContextHandler] started o.s.j.s.ServletContextHandler{/,null}
Apr 21, 2015 19:49:05:952 PM - INFO  [main] [AbstractConnector] Started SocketConnector@0.0.0.0:4444
Apr 21, 2015 19:49:29:930 PM - INFO  [qtp1885828976-12] [AutomationTestRunServlet] Hub is not a dynamic hub -- termination logic will not be started
Apr 21, 2015 19:49:29:936 PM - INFO  [qtp1885828976-12] [AutomationTestRunServlet] Server request received.  Browser [chrome] - Requested Node Count [2] - Request UUID [testRun1]
Apr 21, 2015 19:49:29:940 PM - WARN  [qtp1885828976-12] [AutomationContext] Defaulting node count to 150
Apr 21, 2015 19:49:29:941 PM - INFO  [qtp1885828976-12] [AutomationRunContext] Returning 150 free capacity for the hub
Apr 21, 2015 19:49:29:947 PM - INFO  [qtp1885828976-12] [AutomationRequestMatcher] Returning 0 free slots for request Run Request - UUID: testRun1 - Thread count: 2 - Browser: chrome - OS: linux
Apr 21, 2015 19:49:29:948 PM - WARN  [qtp1885828976-12] [AutomationTestRunServlet] Insufficient nodes to fulfill request. New AMIs will be queued up. Requested [2] - Available [0] - Request UUID [testRun1]
Apr 21, 2015 19:49:29:949 PM - INFO  [qtp1885828976-12] [AutomationTestRunServlet] 2 threads requested
Apr 21, 2015 19:49:29:949 PM - INFO  [qtp1885828976-12] [AutomationTestRunServlet] 1 nodes will be started for run [testRun1]
Apr 21, 2015 19:49:29:957 PM - INFO  [qtp1885828976-12] [AwsVmManager] Setting image id: ami-xxxxxxxx
Apr 21, 2015 19:49:29:957 PM - INFO  [qtp1885828976-12] [AwsVmManager] Setting instance type: c3.large
Apr 21, 2015 19:49:29:957 PM - INFO  [qtp1885828976-12] [AwsVmManager] Setting subnet: subnet-xxxxxxxx
Apr 21, 2015 19:49:29:957 PM - INFO  [qtp1885828976-12] [AwsVmManager] Setting security group: sg-xxxxxxxx
Apr 21, 2015 19:49:29:958 PM - INFO  [qtp1885828976-12] [AwsVmManager] Setting keyname:some@key
Apr 21, 2015 19:49:29:958 PM - INFO  [qtp1885828976-12] [AwsVmManager] Sending run request to AWS...
Apr 21, 2015 19:49:29:961 PM - ERROR [qtp1885828976-12] [AutomationTestRunServlet] Error trying to start nodes: java.lang.NullPointerException
Apr 21, 2015 19:50:29:928 PM - INFO  [pool-2-thread-1] [AutomationRunCleanupTask] Performing cleanup on runs.
Apr 21, 2015 19:50:29:928 PM - WARN  [pool-2-thread-1] [AutomationRunContext] No runs found to clean up
Apr 21, 2015 19:50:29:929 PM - INFO  [pool-3-thread-1] [AutomationNodeCleanupTask] Performing cleanup on nodes.

**Comment by mhardin** [comment]
Hey there.  Can you give exact reproduction steps regarding "populated src/main/resources/aws.properties.default and startGrid with modified var" so I can try it from my end?  Dummy values for sensitive fields are acceptable.

**Comment by mhardin** [comment]
@dquiles I'm wondering if some breaking changes were introduced into the project, around docker and startGrid.  Do you have any luck with the project using commit hash 1cde12c?

**Comment by mhardin** [comment]
Also, I note we're not logging the exception we catch in AutomationTestRunServlet line 226.  I'm going to correct this and get a fix pushed but if you can log this exception locally and put the full stack trace here as well, that will help me figure out whats going wrong.

**Comment by mhardin** [comment]
This should be fixed in https://github.com/RetailMeNot/SeleniumGridScaler/pull/10
